### ISSUE TITLE
tell us about running requirements

### ISSUE THREAD

**Issue by bugbounted** [tamilts124/UdemyFreeV2_24#1]
Hi [Tamil Arasan](https://github.com/tamilts124),
I'm fastly review code & find os-envs requirement inside udemyenroller24.py like ACCESS_TOKEN , SESSION_ID ,CF_CLEARANCE & MYACCESSTOKENS ...
waiting for your readme.md completion
finest regards , samardeh

**Comment by tamilts124** [comment]
Bro first of all i did for myself. i will update dont worry
